export const GET_HAIRCUTS_REQUESTED = 'GET_HAIRCUTS_REQUESTED'
export const GET_HAIRCUTS_SUCCESS = 'GET_HAIRCUTS_SUCCESS'
export const GET_HAIRCUTS_FAILURE = 'GET_HAIRCUTS_FAILURE'

export const UPDATE_BASKET_SUCCESS = 'UPDATE_BASKET_SUCCESS'
export const UPDATE_ADDRESS_SUCCESS = 'UPDATE_ADDRESS_SUCCESS'
export const UPDATE_APPOINTMENT_DATE_SUCCESS = 'UPDATE_APPOINTMENT_DATE_SUCCESS'
